[project]
name = "python-auto-intro-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.11.0.86",
    "pytorch-msssim>=1.0.0",
    "scikit-image>=0.25.2",
]
